"""adición de tabla de tokens y relación con tabla usuarios

Revision ID: da417deae1d2
Revises: 52edd54f03ae
Create Date: 2025-06-12 11:27:56.250393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da417deae1d2'
down_revision: Union[str, None] = '52edd54f03ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_refresco', sa.String(length=255), nullable=False),
    sa.Column('emitido_en', sa.DateTime(), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
